version: '3.8'

services:
  # 1. Serviço de Banco de Dados PostgreSQL
  postgres:
    image: postgres:15-alpine
    container_name: postgres
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      # Mapeia a porta do container para a máquina local (opcional, mas útil para acesso direto)
      - "${POSTGRES_PORT}:5432"

  # 2. Ferramenta de Administração PgAdmin
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      # Porta para acessar o PgAdmin no navegador (ex: http://localhost:5050)
      - "5050:80"
    depends_on:
      - postgres

volumes:
  postgres_data: